# Generated by Django 5.2 on 2026-06-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/banners/')),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField()),
                ('icon_class', models.CharField(help_text='مثال : ti-folder', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمار ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('video_url', models.URLField(blank=True)),
                ('button_text', models.CharField(default='مشاهده دوره ها', max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='about/testimonials/')),
                ('text', models.TextField()),
                ('rate', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نظر دانشجو',
                'verbose_name_plural': 'نظرات دانشجویان',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='about_us.aboutpage')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='about_us.aboutpage')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزیت ها',
                'ordering': ['order'],
            },
        ),
    ]
