# Generated by Django 5.2 on 2026-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='instructors/')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسان',
            },
        ),
    ]
