# Generated by Django 5.2 on 2026-06-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
