# Generated by Django 5.2 on 2026-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Study_program',
            field=models.TextField(blank=True, null=True),
        ),
    ]
