# Generated by Django 5.2 on 2026-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
